version: "3"
services:
    php-apache:
        build:
            context: .
            dockerfile: Dockerfile.php-apache
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: tasklist
            MYSQL_USER: test
            MYSQL_PASSWORD: test

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: test
